AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*

  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideCopsOnly: true

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120
