version: "3.5"

volumes:
  ruby_bundle:

services:
  ruby:
    image: emaiax/ruby
    command: /bin/bash
    working_dir: /playground
    volumes:
      - ./:/playground
      - ruby_bundle:/vendor/bundle
